scrape_configs:
  - job_name: 'vtd-metrics'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [
        '172.17.0.1:8081',
        '172.17.0.1:8080',
        '172.17.0.1:8880',
        '172.17.0.1:8881',
        '172.17.0.1:8882',
        '172.17.0.1:8883',
        ]